services:
  mongodb:
    image: mongo:8
    restart: unless-stopped
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      MONGO_URI: mongodb://mongodb:27017/secure_scholarship_system
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    volumes:
    - ./certs:/certs:ro

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: https://localhost:5000/api
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY: 6Leuel4tAAAAALT1fi7dAMOu1anC78sMa1eOzbUl
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: https://localhost:5000/api
      NEXT_PUBLIC_RECAPTCHA_SITE_KEY: 6Leuel4tAAAAALT1fi7dAMOu1anC78sMa1eOzbUl
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongodb_data:
